---
- name: Temporary file system for temporary directories
  mount:
    path: "{{ item }}"
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: size=2048m
  with_items:
  - "/var/lib/docker/tmp"
  - "/tmp"

- name: Distributed storage mounted
  mount:
    src: "/dev/sdb1"
    path: "/mnt/distributed"
    mode: 0750
    state: mounted
    fstype: ext4
    opts: defaults

- name: Distributed directory exists
  file:
    path: "/mnt/distributed{{ item }}"
    state: directory
    mode: 0750
  with_items:
  - "/var/lib/docker/volumes"
  - "/var/lib/docker/image"

- name: Distributed directory '{{ item }}' bound
  mount:
    path: "{{ item }}"
    src: "/mnt/distributed{{ item }}"
    mode: 0750
    opts: bind
    state: mounted
    fstype: bind
  with_items:
  - "/var/lib/docker/volumes"
  - "/var/lib/docker/image"
