version: '3.6'
services:
  app:
    image: linuxserver/grav
    volumes:
      # Manually add "upload_max_filesize = 20M" to /config/php/php-local.ini !
      - default:/config
      - data:/var/www/html
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.${XYZ}-grav-app.entrypoints=https-ext"
        - "traefik.http.services.${XYZ}-grav-app.loadbalancer.server.port=80"
        #- "traefik.http.routers.${XYZ}-grav-app.rule=Host(`${YOUR-PERSONAL-DOMAIN}`)"

networks:
  proxy:
    name: proxy
    external: true
    
volumes:
  default:
  data:
