version: '3.6'

services:
  app:
    image: nginx
    networks:
      - proxy
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      labels:
        - "traefik.http.services.static-app.loadbalancer.server.port=80"
        - "traefik.http.routers.static-app.entrypoints=https,http,https-ext,http-ext"
        - "traefik.http.routers.static-app.rule=Host(`static.${DOMAIN}`) || Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`)"
        #- "traefik.http.routers.static-app.rule=HostRegexp(`{host:.+}`)"
        #- "traefik.http.routers.static-app.priority=1"

networks:
  proxy:
    name: proxy
    external: true