---
- hosts: appservers # Run_once per swarm
  tasks:
    - run_once: True
      name: docker_stacks
      include_role:
        name: docker_stacks
      loop: "{{ STACKS }}"
      loop_control:
        loop_var: stack