version: '3.6'
services:
  app:
    image: bludit/docker:latest
    volumes:
      - default:/usr/share/nginx/html/bl-content
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.wanno-eu-bludit-app.entrypoints=https"
        - "traefik.http.services.wanno-eu-bludit-app.loadbalancer.server.port=80"
        #- "traefik.http.routers.wanno-eu-bludit-app.rule=Host(`${YOUR-PERSONAL-DOMAIN}`)"

networks:
  proxy:
    name: proxy
    external: true
    
volumes:
  default:
