version: '3.6'
services:
  assistant:
    image: homeassistant/home-assistant:stable
    volumes:
      # Manually configure: https://www.home-assistant.io/integrations/http#reverse-proxies
      # Manually add:
      #  - Printers (e.g., Brother)
      #  - DMSR Slimme meter
      #  - Forecast.Solar
      #  - IKEA TRAD!FRI
      #  - FRITZ!Box stuff
      #  - Kodi
      #  - OpenTherm gateway
      #  - Pi-hole
      #  - Shoppinglist
      #  - Speedtest.net
      #  - Spotify
      #  - ...
      #  - ESPHome ## Doesn't seem to work yet
      - assistant:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - default
    privileged: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.home-assistant.entrypoints=https,https-ext"
        - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      # - target: 9001
      #   published: 9001
      #   protocol: tcp
      #   mode: host
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
    volumes:
      - mosquitto_users:/mosquitto/config/users
      - mosquitto_data:/mosquitto/data
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - proxy
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.tcp.routers.home-mosquitto.entrypoints=mqtts,mqtts-ext"
        - "traefik.tcp.routers.home-mosquitto.tls=true"
        - "traefik.tcp.services.home-mosquitto.loadbalancer.server.port=1883"
        - "traefik.tcp.routers.home-mosquitto.rule=HostSNI(`home.${DOMAIN}`)"

  esphome:
    image: esphome/esphome
    volumes:
      - esphome:/config
    devices:
      - /dev/ttyUSB0    # For flashing
    networks:
      - proxy
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.services.home-esphome.loadbalancer.server.port=6052"
        - "traefik.http.routers.home-esphome.entrypoints=https"
        - "traefik.http.routers.home-esphome.rule=Host(`esphome.${DOMAIN}`)"

networks:
  proxy:
    name: proxy
    external: true
  default:
    
configs:
  mosquitto.conf:
    file: ./mosquitto.conf

volumes:
  assistant:
  esphome:
  mosquitto_users:
  mosquitto_data:
