---
- name: Required Python modules installed (needed for Ansible)
  pip:
    executable: pip3
    name:
    - docker
    - jsondiff

- name: Required system packages installed
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

- name: Docker repository GPG key accepted
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker repository GPG key installed
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Required docker packages installed
  apt:
    update_cache: yes
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Docker daemon configured
  # We'll need to configure the Docker daemon explicitly to
  # - use its internal `docker_gwbridge` network to connect to the pihole we'll deploy later. Docker usually extracts this information from the host's `/etc/resolve.conf`, but this depends on external configuration that's not always correct
  # - to use the 'local' log driver (https://docs.docker.com/config/containers/logging/configure/) to avoid infinitely growing log files
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: Docker running at boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Docker is working (hello world)
  docker_container:
    name: hello-world
    image: hello-world
    detach: false
    cleanup: true
    log_driver: json-file
    output_logs: yes
  register: this
  changed_when: false
  failed_when: "'Hello from Docker!' not in this.container.Output"
