version: '3.6'

services:
  app:
    image: portainer/portainer-ce
    command: --tlsskipverify --host tcp://tasks.agent:9001 --admin-password-file '/run/secrets/admin_password' --edge-compute
    volumes:
      - default:/data
    networks:
      - default
      - proxy
    ports:
      - 9000:9000
      - 8000:8000
    secrets:
      - admin_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.http.routers.portainer-app.entrypoints=https"
        - "traefik.http.services.portainer-app.loadbalancer.server.port=9000"

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
      #CAP_HOST_MANAGEMENT: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - default
    #ports:
    #  - 9001:9001
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=false"


  # agent:
  #   image: portainer/agent:windows1803-amd64
  #   environment:
  #     # REQUIRED: Should be equal to the service name prefixed by "tasks." when
  #     # deployed inside an overlay network
  #     AGENT_CLUSTER_ADDR: tasks.agent
  #     # AGENT_PORT: 9001
  #     # LOG_LEVEL: debug
  #     CAP_HOST_MANAGEMENT: 1
  #   volumes:
  #     - type: npipe
  #       source: \\.\pipe\docker_engine
  #       target: \\.\pipe\docker_engine
  #     # Note: You must create the folder in which you want the data to be persisted before running the following command.
  #     # For example, if you want the data to persist in C:\ProgramData\Portainer you need to create the Portainer directory
  #     # within C:\ProgramData as it does not exist by default.
  #     - type: bind
  #       source: C:\ProgramData\docker\volumes
  #       target: C:\ProgramData\docker\volumes
  #     - type: bind
  #       source: C:\
  #       target: C:\Host
  #   networks:
  #     - default
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #         - node.platform.os == windows

secrets:
  admin_password:
    file: admin_password.secret

volumes:
  default:

networks:
  default:
  proxy:
    name: proxy
    external: true



# https://downloads.portainer.io/portainer-agent-stack.yml
# https://downloads.portainer.io/portainer_windows_stack.yml


# To read: https://docs.docker.com/docker-cloud/apps/service-links/

# https://hub.docker.com/r/v2tec/watchtower/
