version: '3.6'

services:
  app:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_HOSTNAME: keycloak.${DOMAIN}

      KEYCLOAK_USER_FILE: /run/secrets/KEYCLOAK_USER
      KEYCLOAK_PASSWORD_FILE: /run/secrets/KEYCLOAK_PASSWORD
      #KEYCLOAK_FRONTEND_URL: <highly recommended in production>
      #KEYCLOAK_LOGLEVEL: INFO (ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE or WARN)
      # KEYCLOAK_WELCOME_THEME
      # KEYCLOAK_DEFAULT_THEME

      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER_FILE: /run/secrets/KEYCLOAK_DB_USER
      DB_PASSWORD_FILE: /run/secrets/KEYCLOAK_DB_PASSWORD
      
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"

      # This is required to run keycloak behind traefik
      PROXY_ADDRESS_FORWARDING: "true"
    #ports:
    #  - 8080:8080
    networks:
     - default
     - proxy
    depends_on:
     - db
    secrets:
     - KEYCLOAK_USER
     - KEYCLOAK_PASSWORD
     - KEYCLOAK_DB_USER
     - KEYCLOAK_DB_PASSWORD
    deploy:
      replicas: 1
      labels:
        - "traefik.http.services.keycloak-app.loadbalancer.server.port=8080"
        - "traefik.http.routers.keycloak-app.tls.certresolver=letsencrypt"
        - "traefik.http.routers.keycloak-app.entrypoints=http,https"
  db:
    image: postgres
    networks:
     - default
    #ports:
    # - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER_FILE: /run/secrets/KEYCLOAK_DB_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/KEYCLOAK_DB_PASSWORD
    volumes:
     - db:/var/lib/postgresql/data
    secrets:
     - KEYCLOAK_DB_USER
     - KEYCLOAK_DB_PASSWORD

volumes:
  db:

secrets:
  KEYCLOAK_USER:
    external: true
  KEYCLOAK_PASSWORD:
    external: true
  KEYCLOAK_DB_USER:
    external: true
  KEYCLOAK_DB_PASSWORD:
    external: true

networks:
  default:
  proxy:
    external: true