version: "3.6"

services:
  app:
    image: pihole/pihole:v5.8.1
    ports:
      - target: 53    # DNS
        published: 53
        mode: host
      - target: 53    # DNS
        published: 53
        protocol: udp
        mode: host
      - target: 67    # DHCP
        published: 67
        protocol: udp
        mode: host
    #   - "80:80/tcp" # Web interface
    #   - "443:443/tcp" # Web interface
    networks:
      - proxy
    configs:
      - source: localdomain.conf
        target: /etc/dnsmasq.d/02-localdomain.conf
    secrets:
      - webpassword
    environment:
      #QUERY_LOGGING: "true"  # Set to false for improved privacy
      TZ: 'Europe/Amsterdam'
      PROXY_LOCATION: "pihole.${DOMAIN}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      WEBPASSWORD_FILE: /run/secrets/webpassword
      PIHOLE_DNS_: "127.0.0.1;10.0.0.2;${GATEWAY_IP}"

      REV_SERVER: "true"
      REV_SERVER_DOMAIN: "fritz.box"
      REV_SERVER_TARGET: "${GATEWAY_IP}"
      REV_SERVER_CIDR: "${DOMAIN_CIDR}"

      # Configure your network router (e.g., FRITZ!Box) to use this IP as the "Local DNS server"
      # in Home Network > Network > IPv4 Addresses
      ServerIP: "${SWARM_SHARED_IP}"
      #ServerIPv6: ''

      VIRTUAL_HOST: "pihole.${DOMAIN}"
      IPv6: "false"
      DNSMASQ_LISTENING: "all"

      PIHOLE_DOMAIN: "${DOMAIN}"
    volumes:
      - app:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    deploy:
      # mode: global
      replicas: 1
      #placement:
      #  constraints:
      #    - node.role == manager
      labels:
        - "traefik.http.routers.pihole-app.rule=Host(`pihole.${DOMAIN}`) || Host(`pi.hole`)"
        - "traefik.http.routers.pihole-app.entrypoints=https,http"
        - "traefik.http.services.pihole-app.loadbalancer.server.port=80"


configs:
  localdomain.conf:
    file: ./localdomain.conf

secrets:
  webpassword:
    file: webpassword.secret

volumes:
  app:
  dnsmasq:

networks:
  proxy:
    external: true
